version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget.exe restore StopForumSpamApi.sln
build:
  project: StopForumSpamApi.sln
  verbosity: minimal
test:
  assemblies:
    only:
    - StopForumSpamApi.Tests